using System.Collections.Generic;

namespace Booking.Models
{
    /// <summary>
    /// Pre-compiled static catalog containing all 364 security permissions for MEDICO_APP.
    /// Enables instantaneous 0ms UI rendering with zero layout shift.
    /// </summary>
    public static class RoleCatalogDefaults
    {
        public static List<RolePermissionItem> GetDefaultPermissions() => new()
        {
            new RolePermissionItem { Role_id = 365, Main_module = "General", Sub_module = "General", Module = "Dashboard", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 366, Main_module = "OP Portal", Sub_module = "General", Module = "OP Dashboard", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 367, Main_module = "OP Portal", Sub_module = "Patient check-in", Module = "View walkin", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 368, Main_module = "OP Portal", Sub_module = "Patient check-in", Module = "Create walkin", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 369, Main_module = "OP Portal", Sub_module = "Patient check-in", Module = "Edit walkin", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 370, Main_module = "OP Portal", Sub_module = "Patient check-in", Module = "Delete walkin", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 371, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "View walkin", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 372, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "Create walkin", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 373, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "Preview Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 374, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "Print Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 375, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "Preview Casesheet", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 376, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "Print Casesheet", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 377, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "Delete walkin", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 378, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "View vitals", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 379, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "Add vitals", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 380, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "View services", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 381, Main_module = "OP Portal", Sub_module = "Outpatient Visiting", Module = "Create services", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 382, Main_module = "OP Portal", Sub_module = "OP Token Display", Module = "View Token Display", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 383, Main_module = "OP Portal", Sub_module = "Slot Master", Module = "View slot", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 384, Main_module = "OP Portal", Sub_module = "Slot Master", Module = "Create slot", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 385, Main_module = "OP Portal", Sub_module = "Slot Master", Module = "Edit slot", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 386, Main_module = "OP Portal", Sub_module = "Slot Master", Module = "Delete slot", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 387, Main_module = "OP Portal", Sub_module = "Patient Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 388, Main_module = "OP Portal", Sub_module = "Patient Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 389, Main_module = "OP Portal", Sub_module = "Patient Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 390, Main_module = "OP Portal", Sub_module = "Patient Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 391, Main_module = "OP Portal", Sub_module = "Country Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 392, Main_module = "OP Portal", Sub_module = "Country Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 393, Main_module = "OP Portal", Sub_module = "Country Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 394, Main_module = "OP Portal", Sub_module = "Country Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 395, Main_module = "OP Portal", Sub_module = "State Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 396, Main_module = "OP Portal", Sub_module = "State Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 397, Main_module = "OP Portal", Sub_module = "State Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 398, Main_module = "OP Portal", Sub_module = "State Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 399, Main_module = "OP Portal", Sub_module = "City Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 400, Main_module = "OP Portal", Sub_module = "City Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 401, Main_module = "OP Portal", Sub_module = "City Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 402, Main_module = "OP Portal", Sub_module = "City Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 403, Main_module = "OP Portal", Sub_module = "Area Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 404, Main_module = "OP Portal", Sub_module = "Area Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 405, Main_module = "OP Portal", Sub_module = "Area Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 406, Main_module = "OP Portal", Sub_module = "Area Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 407, Main_module = "OP Portal", Sub_module = "Service Type Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 408, Main_module = "OP Portal", Sub_module = "Service Type Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 409, Main_module = "OP Portal", Sub_module = "Service Type Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 410, Main_module = "OP Portal", Sub_module = "Service Type Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 411, Main_module = "IP Portal", Sub_module = "General", Module = "IP Dashboard", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 412, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 413, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 414, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 415, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 416, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "Preview Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 417, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "Download Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 418, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "View Casesheet", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 419, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "Print Casesheet", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 420, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "View Discharge Summary", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 421, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "Create Discharge Summary", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 422, Main_module = "IP Portal", Sub_module = "IP Registration", Module = "Print Discharge Summary", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 423, Main_module = "IP Portal", Sub_module = "Available Beds", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 424, Main_module = "IP Portal", Sub_module = "Available Beds", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 425, Main_module = "IP Portal", Sub_module = "Available Beds", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 426, Main_module = "IP Portal", Sub_module = "Bed Transfer", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 427, Main_module = "IP Portal", Sub_module = "Bed Transfer", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 428, Main_module = "IP Portal", Sub_module = "Discharge Summary", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 429, Main_module = "IP Portal", Sub_module = "Discharge Summary", Module = "Create Discharge Summary", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 430, Main_module = "IP Portal", Sub_module = "Discharge Summary", Module = "Print Discharge Summary", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 431, Main_module = "IP Portal", Sub_module = "Nurse Notes", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 432, Main_module = "IP Portal", Sub_module = "Nurse Notes", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 433, Main_module = "IP Portal", Sub_module = "Nurse Notes", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 434, Main_module = "IP Portal", Sub_module = "Nurse Notes", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 435, Main_module = "IP Portal", Sub_module = "Nurse Notes", Module = "Preview Casesheet", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 436, Main_module = "IP Portal", Sub_module = "Bed Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 437, Main_module = "IP Portal", Sub_module = "Bed Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 438, Main_module = "IP Portal", Sub_module = "Bed Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 439, Main_module = "IP Portal", Sub_module = "Bed Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 440, Main_module = "IP Portal", Sub_module = "Ward Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 441, Main_module = "IP Portal", Sub_module = "Ward Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 442, Main_module = "IP Portal", Sub_module = "Ward Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 443, Main_module = "IP Portal", Sub_module = "Ward Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 444, Main_module = "IP Portal", Sub_module = "Room Type Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 445, Main_module = "IP Portal", Sub_module = "Room Type Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 446, Main_module = "IP Portal", Sub_module = "Room Type Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 447, Main_module = "IP Portal", Sub_module = "Room Type Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 448, Main_module = "IP Portal", Sub_module = "Floor Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 449, Main_module = "IP Portal", Sub_module = "Floor Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 450, Main_module = "IP Portal", Sub_module = "Floor Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 451, Main_module = "IP Portal", Sub_module = "Floor Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 452, Main_module = "IP Portal", Sub_module = "Block Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 453, Main_module = "IP Portal", Sub_module = "Block Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 454, Main_module = "IP Portal", Sub_module = "Block Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 455, Main_module = "IP Portal", Sub_module = "Block Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 456, Main_module = "IP Portal", Sub_module = "Nurse Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 457, Main_module = "IP Portal", Sub_module = "Nurse Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 458, Main_module = "IP Portal", Sub_module = "Nurse Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 459, Main_module = "IP Portal", Sub_module = "Nurse Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 460, Main_module = "IP Portal", Sub_module = "IO Particulars Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 461, Main_module = "IP Portal", Sub_module = "IO Particulars Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 462, Main_module = "IP Portal", Sub_module = "IO Particulars Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 463, Main_module = "IP Portal", Sub_module = "IO Particulars Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 464, Main_module = "IP Portal", Sub_module = "Service Name Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 465, Main_module = "IP Portal", Sub_module = "Service Name Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 466, Main_module = "IP Portal", Sub_module = "Service Name Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 467, Main_module = "IP Portal", Sub_module = "Service Name Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 468, Main_module = "IP Portal", Sub_module = "Schedule Type Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 469, Main_module = "IP Portal", Sub_module = "Schedule Type Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 470, Main_module = "IP Portal", Sub_module = "Schedule Type Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 471, Main_module = "IP Portal", Sub_module = "Schedule Type Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 472, Main_module = "IP Portal", Sub_module = "Discharge Template Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 473, Main_module = "IP Portal", Sub_module = "Discharge Template Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 474, Main_module = "IP Portal", Sub_module = "Discharge Template Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 475, Main_module = "IP Portal", Sub_module = "Discharge Template Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 476, Main_module = "Operation Theatre", Sub_module = "OT Console", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 477, Main_module = "Operation Theatre", Sub_module = "OT Console", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 478, Main_module = "Operation Theatre", Sub_module = "OT Console", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 479, Main_module = "Operation Theatre", Sub_module = "OT Console", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 480, Main_module = "Operation Theatre", Sub_module = "Available Theatre", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 481, Main_module = "Operation Theatre", Sub_module = "Add OT", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 482, Main_module = "Operation Theatre", Sub_module = "Add OT", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 483, Main_module = "Operation Theatre", Sub_module = "Add OT", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 484, Main_module = "Operation Theatre", Sub_module = "Add OT", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 485, Main_module = "Operation Theatre", Sub_module = "Fee Categories", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 486, Main_module = "Operation Theatre", Sub_module = "Fee Categories", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 487, Main_module = "Operation Theatre", Sub_module = "Fee Categories", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 488, Main_module = "Operation Theatre", Sub_module = "Fee Categories", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 489, Main_module = "Billing Portal", Sub_module = "Billing Portal", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 490, Main_module = "Billing Portal", Sub_module = "Billing Portal", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 491, Main_module = "Billing Portal", Sub_module = "Due Collection", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 492, Main_module = "Billing Portal", Sub_module = "Due Collection", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 493, Main_module = "Billing Portal", Sub_module = "Due Collection History", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 494, Main_module = "Billing Portal", Sub_module = "Due Collection History", Module = "Print Patient Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 495, Main_module = "Billing Portal", Sub_module = "Due Collection History", Module = "Print Payment Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 496, Main_module = "Billing Portal", Sub_module = "Due Collection History", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 497, Main_module = "Billing Portal", Sub_module = "Patient Advance", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 498, Main_module = "Billing Portal", Sub_module = "Patient Advance", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 499, Main_module = "Billing Portal", Sub_module = "Bill List", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 500, Main_module = "Billing Portal", Sub_module = "Bill List", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 501, Main_module = "Billing Portal", Sub_module = "Bill List", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 502, Main_module = "Billing Portal", Sub_module = "Bill List", Module = "Print Consolidated OP Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 503, Main_module = "Billing Portal", Sub_module = "Bill List", Module = "Print Consolidated IP Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 504, Main_module = "Billing Portal", Sub_module = "Bill List", Module = "Print Overall Consolidated Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 505, Main_module = "Billing Portal", Sub_module = "Bill Summary", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 506, Main_module = "Billing Portal", Sub_module = "Bill Summary", Module = "Print Patient Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 507, Main_module = "Billing Portal", Sub_module = "Cash Counter", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 508, Main_module = "Billing Portal", Sub_module = "Cash Counter", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 509, Main_module = "Billing Portal", Sub_module = "Counter Shift", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 510, Main_module = "Billing Portal", Sub_module = "Counter Shift", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 511, Main_module = "Billing Portal", Sub_module = "Counter Shift", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 512, Main_module = "Billing Portal", Sub_module = "Bill No Sequence", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 513, Main_module = "Billing Portal", Sub_module = "Bill No Sequence", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 514, Main_module = "Billing Portal", Sub_module = "Bill No Sequence", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 515, Main_module = "Billing Portal", Sub_module = "Bill No Sequence", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 516, Main_module = "Billing Portal", Sub_module = "Fee Type Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 517, Main_module = "Billing Portal", Sub_module = "Fee Type Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 518, Main_module = "Billing Portal", Sub_module = "Fee Type Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 519, Main_module = "Billing Portal", Sub_module = "Fee Type Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 520, Main_module = "Billing Portal", Sub_module = "Counter Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 521, Main_module = "Billing Portal", Sub_module = "Counter Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 522, Main_module = "Billing Portal", Sub_module = "Counter Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 523, Main_module = "Billing Portal", Sub_module = "Counter Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 524, Main_module = "Billing Portal", Sub_module = "Paymode Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 525, Main_module = "Billing Portal", Sub_module = "Paymode Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 526, Main_module = "Billing Portal", Sub_module = "Paymode Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 527, Main_module = "Billing Portal", Sub_module = "Paymode Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 528, Main_module = "Billing Portal", Sub_module = "Test Fee Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 529, Main_module = "Billing Portal", Sub_module = "Test Fee Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 530, Main_module = "Billing Portal", Sub_module = "Test Fee Master", Module = "Print Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 531, Main_module = "Billing Portal", Sub_module = "Reimbursement Co", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 532, Main_module = "Billing Portal", Sub_module = "Reimbursement Co", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 533, Main_module = "Billing Portal", Sub_module = "Reimbursement Co", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 534, Main_module = "Billing Portal", Sub_module = "Reimbursement Co", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 535, Main_module = "Laboratory", Sub_module = "Result Search", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 536, Main_module = "Laboratory", Sub_module = "Result Search", Module = "Print Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 537, Main_module = "Laboratory", Sub_module = "Result Entry", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 538, Main_module = "Laboratory", Sub_module = "Result Entry", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 539, Main_module = "Laboratory", Sub_module = "Result Entry", Module = "Authorize", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 540, Main_module = "Laboratory", Sub_module = "Result Entry", Module = "Preview Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 541, Main_module = "Laboratory", Sub_module = "Result Entry", Module = "Print Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 542, Main_module = "Laboratory", Sub_module = "Test Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 543, Main_module = "Laboratory", Sub_module = "Test Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 544, Main_module = "Laboratory", Sub_module = "Test Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 545, Main_module = "Laboratory", Sub_module = "Test Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 546, Main_module = "Laboratory", Sub_module = "Bill Items", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 547, Main_module = "Laboratory", Sub_module = "Bill Items", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 548, Main_module = "Laboratory", Sub_module = "Bill Items", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 549, Main_module = "Laboratory", Sub_module = "Bill Items", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 550, Main_module = "Laboratory", Sub_module = "Test Fee Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 551, Main_module = "Laboratory", Sub_module = "Test Fee Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 552, Main_module = "Laboratory", Sub_module = "Test Fee Master", Module = "Print Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 553, Main_module = "Laboratory", Sub_module = "Test Type Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 554, Main_module = "Laboratory", Sub_module = "Test Type Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 555, Main_module = "Laboratory", Sub_module = "Test Type Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 556, Main_module = "Laboratory", Sub_module = "Test Type Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 557, Main_module = "Laboratory", Sub_module = "Group Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 558, Main_module = "Laboratory", Sub_module = "Group Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 559, Main_module = "Laboratory", Sub_module = "Group Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 560, Main_module = "Laboratory", Sub_module = "Group Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 561, Main_module = "Laboratory", Sub_module = "Report Methods", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 562, Main_module = "Laboratory", Sub_module = "Report Methods", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 563, Main_module = "Laboratory", Sub_module = "Report Methods", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 564, Main_module = "Laboratory", Sub_module = "Report Methods", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 565, Main_module = "Laboratory", Sub_module = "Specimen Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 566, Main_module = "Laboratory", Sub_module = "Specimen Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 567, Main_module = "Laboratory", Sub_module = "Specimen Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 568, Main_module = "Laboratory", Sub_module = "Specimen Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 569, Main_module = "Laboratory", Sub_module = "UOM Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 570, Main_module = "Laboratory", Sub_module = "UOM Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 571, Main_module = "Laboratory", Sub_module = "UOM Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 572, Main_module = "Laboratory", Sub_module = "UOM Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 573, Main_module = "Laboratory", Sub_module = "Machine Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 574, Main_module = "Laboratory", Sub_module = "Machine Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 575, Main_module = "Laboratory", Sub_module = "Machine Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 576, Main_module = "Laboratory", Sub_module = "Machine Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 577, Main_module = "Pharmacy", Sub_module = "General", Module = "Pharmacy Dashboard", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 578, Main_module = "Pharmacy", Sub_module = "Pharmacy Billing", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 579, Main_module = "Pharmacy", Sub_module = "Pharmacy Billing", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 580, Main_module = "Pharmacy", Sub_module = "Pharmacy Billing", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 581, Main_module = "Pharmacy", Sub_module = "Pharmacy Billing", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 582, Main_module = "Pharmacy", Sub_module = "Pharmacy Billing", Module = "Print Bill Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 583, Main_module = "Pharmacy", Sub_module = "Pharmacy Billing", Module = "Preview Sales Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 584, Main_module = "Pharmacy", Sub_module = "Pharmacy Billing", Module = "Print Sales Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 585, Main_module = "Pharmacy", Sub_module = "Sales Return", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 586, Main_module = "Pharmacy", Sub_module = "Sales Return", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 587, Main_module = "Pharmacy", Sub_module = "Pharmacy Reports", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 588, Main_module = "Pharmacy", Sub_module = "Pharmacy Reports", Module = "Preview Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 589, Main_module = "Pharmacy", Sub_module = "Pharmacy Reports", Module = "Print Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 590, Main_module = "Inventory", Sub_module = "Purchase", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 591, Main_module = "Inventory", Sub_module = "Purchase", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 592, Main_module = "Inventory", Sub_module = "Purchase", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 593, Main_module = "Inventory", Sub_module = "Purchase", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 594, Main_module = "Inventory", Sub_module = "Purchase Return", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 595, Main_module = "Inventory", Sub_module = "Purchase Return", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 596, Main_module = "Inventory", Sub_module = "Purchase Payments", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 597, Main_module = "Inventory", Sub_module = "Purchase Payments", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 598, Main_module = "Inventory", Sub_module = "Indent Request", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 599, Main_module = "Inventory", Sub_module = "Indent Request", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 600, Main_module = "Inventory", Sub_module = "Indent Request", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 601, Main_module = "Inventory", Sub_module = "Indent Request", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 602, Main_module = "Inventory", Sub_module = "Indent Approval", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 603, Main_module = "Inventory", Sub_module = "Indent Approval", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 604, Main_module = "Inventory", Sub_module = "Stock", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 605, Main_module = "Inventory", Sub_module = "Stock", Module = "Preview Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 606, Main_module = "Inventory", Sub_module = "Stock", Module = "Print Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 607, Main_module = "Inventory", Sub_module = "Stock Adjustment", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 608, Main_module = "Inventory", Sub_module = "Stock Adjustment", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 609, Main_module = "Inventory", Sub_module = "Issue Stock", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 610, Main_module = "Inventory", Sub_module = "Issue Stock", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 611, Main_module = "Inventory", Sub_module = "Issue Stock", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 612, Main_module = "Inventory", Sub_module = "Issue Stock", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 613, Main_module = "Inventory", Sub_module = "Receive Stock", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 614, Main_module = "Inventory", Sub_module = "Receive Stock", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 615, Main_module = "Inventory", Sub_module = "Transfer Register", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 616, Main_module = "Inventory", Sub_module = "Doctor Consumption", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 617, Main_module = "Inventory", Sub_module = "Doctor Consumption", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 618, Main_module = "Inventory", Sub_module = "Item Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 619, Main_module = "Inventory", Sub_module = "Item Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 620, Main_module = "Inventory", Sub_module = "Item Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 621, Main_module = "Inventory", Sub_module = "Item Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 622, Main_module = "Inventory", Sub_module = "Category Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 623, Main_module = "Inventory", Sub_module = "Category Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 624, Main_module = "Inventory", Sub_module = "Category Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 625, Main_module = "Inventory", Sub_module = "Category Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 626, Main_module = "Inventory", Sub_module = "Item Type Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 627, Main_module = "Inventory", Sub_module = "Item Type Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 628, Main_module = "Inventory", Sub_module = "Item Type Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 629, Main_module = "Inventory", Sub_module = "Item Type Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 630, Main_module = "Inventory", Sub_module = "Vendor Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 631, Main_module = "Inventory", Sub_module = "Vendor Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 632, Main_module = "Inventory", Sub_module = "Vendor Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 633, Main_module = "Inventory", Sub_module = "Vendor Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 634, Main_module = "Inventory", Sub_module = "Unit Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 635, Main_module = "Inventory", Sub_module = "Unit Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 636, Main_module = "Inventory", Sub_module = "Unit Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 637, Main_module = "Inventory", Sub_module = "Unit Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 638, Main_module = "Inventory", Sub_module = "Store Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 639, Main_module = "Inventory", Sub_module = "Store Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 640, Main_module = "Inventory", Sub_module = "Store Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 641, Main_module = "Inventory", Sub_module = "Store Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 642, Main_module = "Inventory", Sub_module = "Manufacturer Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 643, Main_module = "Inventory", Sub_module = "Manufacturer Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 644, Main_module = "Inventory", Sub_module = "Manufacturer Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 645, Main_module = "Inventory", Sub_module = "Manufacturer Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 646, Main_module = "Inventory", Sub_module = "Ledger Group", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 647, Main_module = "Inventory", Sub_module = "Ledger Group", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 648, Main_module = "Inventory", Sub_module = "Ledger Group", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 649, Main_module = "Inventory", Sub_module = "Ledger Group", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 650, Main_module = "Inventory", Sub_module = "Ledger Type", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 651, Main_module = "Inventory", Sub_module = "Ledger Type", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 652, Main_module = "Inventory", Sub_module = "Ledger Type", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 653, Main_module = "Inventory", Sub_module = "Ledger Type", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 654, Main_module = "Doctor Portal", Sub_module = "Doctor Patient List", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 655, Main_module = "Doctor Portal", Sub_module = "Doctor Patient List", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 656, Main_module = "Doctor Portal", Sub_module = "Doctor Patient List", Module = "Finalize Casesheet", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 657, Main_module = "Doctor Portal", Sub_module = "Doctor Patient List", Module = "Print Casesheet", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 658, Main_module = "Doctor Portal", Sub_module = "Doctor Status", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 659, Main_module = "Doctor Portal", Sub_module = "Doctor Status", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 660, Main_module = "Doctor Portal", Sub_module = "Doctor Status", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 661, Main_module = "Doctor Portal", Sub_module = "Slot Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 662, Main_module = "Doctor Portal", Sub_module = "Slot Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 663, Main_module = "Doctor Portal", Sub_module = "Slot Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 664, Main_module = "Doctor Portal", Sub_module = "Slot Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 665, Main_module = "Doctor Portal", Sub_module = "Doctors Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 666, Main_module = "Doctor Portal", Sub_module = "Doctors Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 667, Main_module = "Doctor Portal", Sub_module = "Doctors Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 668, Main_module = "Doctor Portal", Sub_module = "Doctors Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 669, Main_module = "Doctor Portal", Sub_module = "Slot Type Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 670, Main_module = "Doctor Portal", Sub_module = "Slot Type Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 671, Main_module = "Doctor Portal", Sub_module = "Slot Type Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 672, Main_module = "Doctor Portal", Sub_module = "Slot Type Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 673, Main_module = "Doctor Portal", Sub_module = "Doctor Type Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 674, Main_module = "Doctor Portal", Sub_module = "Doctor Type Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 675, Main_module = "Doctor Portal", Sub_module = "Doctor Type Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 676, Main_module = "Doctor Portal", Sub_module = "Doctor Type Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 677, Main_module = "Doctor Portal", Sub_module = "Doctor Speciality Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 678, Main_module = "Doctor Portal", Sub_module = "Doctor Speciality Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 679, Main_module = "Doctor Portal", Sub_module = "Doctor Speciality Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 680, Main_module = "Doctor Portal", Sub_module = "Doctor Speciality Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 681, Main_module = "Doctor Portal", Sub_module = "Reimbursement Co", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 682, Main_module = "Doctor Portal", Sub_module = "Reimbursement Co", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 683, Main_module = "Doctor Portal", Sub_module = "Reimbursement Co", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 684, Main_module = "Doctor Portal", Sub_module = "Reimbursement Co", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 685, Main_module = "Vitals", Sub_module = "General", Module = "Vitals Dashboard", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 686, Main_module = "Vitals", Sub_module = "Vitals Entry", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 687, Main_module = "Vitals", Sub_module = "Vitals Entry", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 688, Main_module = "Vitals", Sub_module = "Vitals Entry", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 689, Main_module = "Vitals", Sub_module = "Vitals Entry", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 690, Main_module = "Vitals", Sub_module = "Lab Test Entry", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 691, Main_module = "Vitals", Sub_module = "Lab Test Entry", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 692, Main_module = "Vitals", Sub_module = "Lab Test Entry", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 693, Main_module = "Vitals", Sub_module = "Scan Result Entry", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 694, Main_module = "Vitals", Sub_module = "Scan Result Entry", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 695, Main_module = "Vitals", Sub_module = "Scan Result Entry", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 696, Main_module = "Vitals", Sub_module = "Token Display Screen", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 697, Main_module = "Vitals", Sub_module = "Appointment Pre-Booking", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 698, Main_module = "Vitals", Sub_module = "Appointment Pre-Booking", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 699, Main_module = "Vitals", Sub_module = "Appointment Pre-Booking", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 700, Main_module = "Vitals", Sub_module = "Appointment Pre-Booking", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 701, Main_module = "Vitals", Sub_module = "Reception Portal", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 702, Main_module = "Vitals", Sub_module = "Reception Portal", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 703, Main_module = "Vitals", Sub_module = "OG Screen", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 704, Main_module = "Vitals", Sub_module = "OG Screen", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 705, Main_module = "Vitals", Sub_module = "Doctor Group Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 706, Main_module = "Vitals", Sub_module = "Doctor Group Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 707, Main_module = "Vitals", Sub_module = "Doctor Group Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 708, Main_module = "Vitals", Sub_module = "Doctor Group Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 709, Main_module = "Admin Portal", Sub_module = "User Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 710, Main_module = "Admin Portal", Sub_module = "User Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 711, Main_module = "Admin Portal", Sub_module = "User Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 712, Main_module = "Admin Portal", Sub_module = "User Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 713, Main_module = "Admin Portal", Sub_module = "User Rights", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 714, Main_module = "Admin Portal", Sub_module = "User Rights", Module = "Create & Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 715, Main_module = "Admin Portal", Sub_module = "Product & Feature Registry", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 716, Main_module = "Admin Portal", Sub_module = "Product & Feature Registry", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 717, Main_module = "Admin Portal", Sub_module = "Product & Feature Registry", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 718, Main_module = "Admin Portal", Sub_module = "Product & Feature Registry", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 719, Main_module = "Admin Portal", Sub_module = "Branch Master", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 720, Main_module = "Admin Portal", Sub_module = "Branch Master", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 721, Main_module = "Admin Portal", Sub_module = "Branch Master", Module = "Edit", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 722, Main_module = "Admin Portal", Sub_module = "Branch Master", Module = "Delete", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 723, Main_module = "Admin Portal", Sub_module = "Settings", Module = "View", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 724, Main_module = "Admin Portal", Sub_module = "Settings", Module = "Create", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 725, Main_module = "Billing Portal", Sub_module = "Billing Portal", Module = "Edit Qty", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 726, Main_module = "Billing Portal", Sub_module = "Billing Portal", Module = "Edit Consession", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 727, Main_module = "Billing Portal", Sub_module = "Reports", Module = "Preview Report", Product_id = "MEDICO_APP" },
            new RolePermissionItem { Role_id = 728, Main_module = "Billing Portal", Sub_module = "Reports", Module = "Print Report", Product_id = "MEDICO_APP" },
        };
    }
}
